export const pets = [
    {
        identificador: 1,
        nome: "Thor",
        imagem: "thor.jpg",
        descricao: "Cachorro dócil e brincalhão, muito sociável.",
        raca: "Golden Retriever",
        idade: 3.5,
        peso: 28.4,
        genero: "macho",
        tipo_pet: "cachorro",
        status: "disponivel",
        dataCadastro: "2026-09-01T10:30:00"
    },
    {
        identificador: 2,
        nome: "Luna",
        imagem: "luna.jpg",
        descricao: "Cadela carinhosa e tranquila, ideal para família.",
        raca: "Labrador",
        idade: 2,
        peso: 24.7,
        genero: "femea",
        tipo_pet: "cachorro",
        status: "disponivel",
        dataCadastro: "2026-09-03T14:20:00"
    },
    {
        identificador: 3,
        nome: "Mingau",
        imagem: "mingau.jpg",
        descricao: "Gato calmo e independente, gosta de ambientes tranquilos.",
        raca: "SRD",
        idade: 1.5,
        peso: 4.2,
        genero: "macho",
        tipo_pet: "gato",
        status: "pendente",
        dataCadastro: "2026-09-05T09:15:00"
    },
    {
        identificador: 4,
        nome: "Mel",
        imagem: "mel.jpg",
        descricao: "Cachorra brincalhona e muito afetuosa.",
        raca: "Poodle",
        idade: 5,
        peso: 8.6,
        genero: "femea",
        tipo_pet: "cachorro",
        status: "adotado",
        dataCadastro: "2026-08-20T16:40:00"
    },
    {
        identificador: 5,
        nome: "Simba",
        imagem: "simba.jpg",
        descricao: "Gato curioso e brincalhão, gosta de atenção.",
        raca: "Siamês",
        idade: 3,
        peso: 4.8,
        genero: "macho",
        tipo_pet: "gato",
        status: "disponivel",
        dataCadastro: "2026-09-07T11:00:00"
    },
    {
        identificador: 6,
        nome: "Nina",
        imagem: "nina.jpg",
        descricao: "Gata dócil e carinhosa, acostumada com pessoas.",
        raca: "SRD",
        idade: 2.5,
        peso: 3.9,
        genero: "femea",
        tipo_pet: "gato",
        status: "disponivel",
        dataCadastro: "2026-09-08T13:25:00"
    },
    {
        identificador: 7,
        nome: "Max",
        imagem: "max.jpg",
        descricao: "Cachorro energético que adora correr e brincar.",
        raca: "Border Collie",
        idade: 4,
        peso: 19.3,
        genero: "macho",
        tipo_pet: "cachorro",
        status: "pendente",
        dataCadastro: "2026-09-10T08:50:00"
    },
    {
        identificador: 8,
        nome: "Amora",
        imagem: "amora.jpg",
        descricao: "Cadela tranquila, carinhosa e muito obediente.",
        raca: "Beagle",
        idade: 6,
        peso: 11.8,
        genero: "femea",
        tipo_pet: "cachorro",
        status: "disponivel",
        dataCadastro: "2026-09-11T15:10:00"
    },
    {
        identificador: 9,
        nome: "Oliver",
        imagem: "oliver.jpg",
        descricao: "Gato jovem e brincalhão, bastante sociável.",
        raca: "Persa",
        idade: 1,
        peso: 3.7,
        genero: "macho",
        tipo_pet: "gato",
        status: "disponivel",
        dataCadastro: "2026-09-12T10:45:00"
    },
    {
        identificador: 10,
        nome: "Belinha",
        imagem: "belinha.jpg",
        descricao: "Cachorra pequena e carinhosa, gosta de colo.",
        raca: "Shih-tzu",
        idade: 4.5,
        peso: 6.2,
        genero: "femea",
        tipo_pet: "cachorro",
        status: "adotado",
        dataCadastro: "2026-08-15T12:30:00"
    }
];